<?php
$title = "Compose Message";
$this->headTitle($title);
if($this->htMessagingOptions()->getEnableMultipleReceivers()) {
    $this->inlineScript()->appendFile($this->basePath()."/ht-messaging/js/ui.multiselect.js"); 
    $this->headLink()->appendStylesheet($this->basePath()."/ht-messaging/css/ui.multiselect.css");    
} else {
    $this->inlineScript()->appendFile($this->basePath()."/ht-messaging/js/select2.js"); 
}
?>
<h2><?php echo $title; ?></h2>
<br/>
<?php if($messageSent): ?>
<div class="alert alert-success">Message Sent Successfully</div>
<?php endif; ?>
<?php echo $this->form()->openTag($form); ?>
<span><?php echo $this->formLabel($form->get('receiver_id')) ?></span><br/>
<div><?php echo $this->formElement($form->get('receiver_id')).$this->formElementErrors($form->get('receiver_id')) ?></div>

<span><?php echo $this->formLabel($form->get('subject')) ?></span><br/>
<div><?php echo $this->formElement($form->get('subject')).$this->formElementErrors($form->get('subject')) ?></div>

<span><?php echo $this->formLabel($form->get('message_text')) ?></span><br/>
<div><?php echo $this->formElement($form->get('message_text')).$this->formElementErrors($form->get('message_text')) ?></div>
<br/>
<div><?php echo $this->formElement($form->get('submit')) ?></div>
<?php echo $this->form()->closeTag($form); ?>
<br/>
<script type="text/javascript">
    $(function () {
        <?php if($this->htMessagingOptions()->getEnableMultipleReceivers()): ?>
            $("input[name='receiver_id']").multiselect({
                dividerLocation: 0.5
            });
        <?php else: ?>
            $("input[name='receiver_id']").select2();    
        <?php endif; ?>        
    });
</script>
