<?php
//$subTitle = "Message By " . $this->zfcUserDisplayName($sender);
$title = $message->getSubject();
$title = $this->escapeHtml($title);
$this->headTitle($title);
?>
<h2><?php echo $title; ?></h2>
<br/>
<div class="alert alert-info">
    <span><b>Sender</b> : <?php echo $this->zfcUserDisplayName($sender); ?></span>
    <span class="pull-right">
        <?php
            $dateObject = new \DateTime($messageReceiver->getSentDateTime());
            echo $dateObject->format('l, jS F Y  h:i A');
        ?>
    </span>
</div>
<br/>
<div class="well">
    <?php echo $this->escapeHtml($message->getMessageText()); ?>
</div>
