<?php
    $title = ucfirst($type) . " Messages";
    $title = $this->escapeHtml($title);
    $this->headTitle($title);
?>
<h2><?= $title ?></h2>
<br/>
<?php if ($type === 'inbox' || $type === 'unread'): ?>
    <div class="btn-group">
        <a class="btn btn-default mark-all">Mark All</a> 
        <a class="btn btn-default unmark-all">Unmark All</a> 
        <a class="btn btn-default read-unread" data-new-value="read">Mark as read</a> 
        <a class="btn btn-default read-unread" data-new-value="unread">Mark as unread</a> 
    </div>
<?php endif; ?>
<?php foreach ($messages as $message): ?>
    <div class="well">
    
    </div>
<?php endforeach; ?>
