<?php
$title = $this->escapeHtml($message->getSubject());
$this->headTitle($title);
?>
<h2><?php echo $title; ?></h2>
<br/>
<div class="alert alert-info">
    <?php if (isset($receiver)): ?>
        <span><b>Receiver</b> : <?php echo $this->zfcUserDisplayName($receiver); ?></span>
    <?php else: ?>
        <span><b>Receivers Count:<?php echo count($messageReceivers); ?></b></span>
        <span><a href="<?php echo $this->url('htmessaging/receivers', array('message_id' => $message->getId())); ?>">View Receivers</a></span>
    <?php endif; ?>
    <span class="pull-right">
        <?php
            $dateObject = new \DateTime($message->getCreatedDateTime());
            echo $dateObject->format('l, jS F Y  h:i A');
        ?>
    </span>
</div>
<div class="well">
    <?php echo $this->escapeHtml($message->getMessageText()); ?>
</div>
